# Site settings
title: Space Apps Exeter
email: contact@spaceappsexeter.org
description: > # this means to ignore newlines until "baseurl:"
  Once again the Met Office is proud to be hosting NASA's Space Apps Challenge.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spaceappsexeter.org/" # the base hostname & protocol for your site

collections:
  challenges:
    title: Challenges
    output: true

# User setting
social:
  twitter: spaceappsexeter
  flickr: spaceappsexeter

address:
  - line: "Met Office"
  - line: "Fitzroy Road, Exeter, Devon, EX1 3PB"
copyright: Space Apps Exeter

# API settings
google_api_key: AIzaSyC27hz24IBSijJOzkQfou9PD8hfw3E9b0M
google_analytics: UA-72192919-1

# Build settings
markdown: kramdown

#build output dir
destination: _site

#exclude from build
exclude: ["bower.json",
          "Gemfile*",
          "package.json",
          "README.md",
          "LICENSE.md",
          "Gruntfile.js",
          "node_modules",
          "bower_components",
          "tests"]

#sass config
sass:
  sass_dir: _sass
  style: compressed
